#!/bin/bash

# Must execute dev/setup-containers before running

PROJECT_DIR="$(cd "`dirname $0`"/..; pwd)"
cd $PROJECT_DIR

. $PROJECT_DIR/dev/check-containers

sbt clean coverage integration:test
sbt coverageReport

unset CONTAINER_HOST
