#!/bin/bash

# Script will run both unit tests and integration tests.
# Must execute dev/setup-containers before running

PROJECT_DIR="$(cd "`dirname $0`"/..; pwd)"
cd $PROJECT_DIR

. $PROJECT_DIR/dev/check-containers

sbt clean coverage test integration:test
sbt coverageReport

unset CONTAINER_HOST
echo "Stopping and removing container images..."
docker stop $orientdb_name $rabbitmq_name &>/dev/null
docker rm   $orientdb_name $rabbitmq_name &>/dev/null
docker rmi  myapp/orientdb myapp/rabbitmq &>/dev/null
rm -rf $PROJECT_DIR/databases
echo "Done"
