FROM ubuntu

RUN apt-get update &&  \
    apt-get install -y \
      openjdk-8-jdk    \
      wget             \
      curl             \
      iputils-ping     \
      net-tools        \
      dnsutils         \
      python
