// DO NOT EDIT: code generated by 'jsoner' on 2018-08-21 21:48:46.675951432 +0000 UTC

package main

func (Foo) AvroSchema() avro.Schema {
	return `{
                "type": "record",
                "name": "Foo",
                "fields": [
			{"name": "id", "type": "long", "default": 0},
			{"name": "name", "type": "string", "default": ""},
			{"name": "quick_alias", "type": "string", "default": ""},
                ]
        }`
}
