# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: solver.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='solver.proto',
  package='solver',
  syntax='proto3',
  serialized_pb=_b('\n\x0csolver.proto\x12\x06solver\"0\n\rSolverRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\x12\t\n\x01\x63\x18\x03 \x01(\x01\"&\n\x0eSolverResponse\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x32K\n\x06Solver\x12\x41\n\x0eSolveQuadratic\x12\x15.solver.SolverRequest\x1a\x16.solver.SolverResponse\"\x00\x62\x06proto3')
)




_SOLVERREQUEST = _descriptor.Descriptor(
  name='SolverRequest',
  full_name='solver.SolverRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='solver.SolverRequest.a', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='solver.SolverRequest.b', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='c', full_name='solver.SolverRequest.c', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=72,
)


_SOLVERRESPONSE = _descriptor.Descriptor(
  name='SolverResponse',
  full_name='solver.SolverResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='solver.SolverResponse.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='solver.SolverResponse.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['SolverRequest'] = _SOLVERREQUEST
DESCRIPTOR.message_types_by_name['SolverResponse'] = _SOLVERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SolverRequest = _reflection.GeneratedProtocolMessageType('SolverRequest', (_message.Message,), dict(
  DESCRIPTOR = _SOLVERREQUEST,
  __module__ = 'solver_pb2'
  # @@protoc_insertion_point(class_scope:solver.SolverRequest)
  ))
_sym_db.RegisterMessage(SolverRequest)

SolverResponse = _reflection.GeneratedProtocolMessageType('SolverResponse', (_message.Message,), dict(
  DESCRIPTOR = _SOLVERRESPONSE,
  __module__ = 'solver_pb2'
  # @@protoc_insertion_point(class_scope:solver.SolverResponse)
  ))
_sym_db.RegisterMessage(SolverResponse)



_SOLVER = _descriptor.ServiceDescriptor(
  name='Solver',
  full_name='solver.Solver',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=114,
  serialized_end=189,
  methods=[
  _descriptor.MethodDescriptor(
    name='SolveQuadratic',
    full_name='solver.Solver.SolveQuadratic',
    index=0,
    containing_service=None,
    input_type=_SOLVERREQUEST,
    output_type=_SOLVERRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOLVER)

DESCRIPTOR.services_by_name['Solver'] = _SOLVER

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class SolverStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.SolveQuadratic = channel.unary_unary(
          '/solver.Solver/SolveQuadratic',
          request_serializer=SolverRequest.SerializeToString,
          response_deserializer=SolverResponse.FromString,
          )


  class SolverServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def SolveQuadratic(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_SolverServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'SolveQuadratic': grpc.unary_unary_rpc_method_handler(
            servicer.SolveQuadratic,
            request_deserializer=SolverRequest.FromString,
            response_serializer=SolverResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'solver.Solver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaSolverServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def SolveQuadratic(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaSolverStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def SolveQuadratic(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    SolveQuadratic.future = None


  def beta_create_Solver_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('solver.Solver', 'SolveQuadratic'): SolverRequest.FromString,
    }
    response_serializers = {
      ('solver.Solver', 'SolveQuadratic'): SolverResponse.SerializeToString,
    }
    method_implementations = {
      ('solver.Solver', 'SolveQuadratic'): face_utilities.unary_unary_inline(servicer.SolveQuadratic),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Solver_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('solver.Solver', 'SolveQuadratic'): SolverRequest.SerializeToString,
    }
    response_deserializers = {
      ('solver.Solver', 'SolveQuadratic'): SolverResponse.FromString,
    }
    cardinalities = {
      'SolveQuadratic': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'solver.Solver', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
