# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import solver_pb2 as solver__pb2


class SolverStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SolveQuadratic = channel.unary_unary(
        '/solver.Solver/SolveQuadratic',
        request_serializer=solver__pb2.SolverRequest.SerializeToString,
        response_deserializer=solver__pb2.SolverResponse.FromString,
        )


class SolverServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SolveQuadratic(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SolverServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SolveQuadratic': grpc.unary_unary_rpc_method_handler(
          servicer.SolveQuadratic,
          request_deserializer=solver__pb2.SolverRequest.FromString,
          response_serializer=solver__pb2.SolverResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'solver.Solver', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
