# Pull base image.
FROM ubuntu

# Install Sun JDK 8
RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer

# Install sbt manually
COPY ./project/build.properties /myapp/project/build.properties
RUN eval $(sed s/sbt.version/SBT_VERSION/ </myapp/project/build.properties) && \
    mkdir -p /usr/local/bin && \
    wget -P /usr/local/bin/ https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/$SBT_VERSION/sbt-launch.jar
COPY project/sbt /usr/local/bin/
RUN chmod +x /usr/local/bin/sbt

# Define working directory.
WORKDIR /myapp

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

# Define default command.
CMD ["bash"]
